//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaperMaster
    {
        public long ID { get; set; }
        public int EducationLevelID { get; set; }
        public int SubjectID { get; set; }
        public int SyllabusYear { get; set; }
        public int PaperYear { get; set; }
        public string PaperCode { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public long UserID { get; set; }
        public int PaperTypeId { get; set; }
        public string PrioirtyRollNoStartsWith { get; set; }
    }
}
